title: Valores Globales
menu:
  image: base/logo-h.svg
  items:
  - link: /
    label: Inicio
  - link: /casas-pasivas/
    label: Casas Pasivas
  - link: /proyectos/
    label: Proyectos
  - link: /fardo/
    label: Fardo
  - link: /#contacto
    label: Contacto
    button: cta
  - link: https://agroecologiamurcia.org/
    label: Formación
    button: main
projects:
- image: casas-pasivas-2024-07-17-08-24-31.jpg
  id: proyecto-1
  link: '#proyecto-1'
  title: Proyecto 1
  md: |+
    ***VIVIENDA UNIFAMILIAR :  CON CARBONO NEGATIVO ACUMULADO DE 2.100 kg de C2e***

    ***AÑO CONSTRUCCION: 2023***

    ***M2 CONSTRUIDOS : 92 / UTILES: 82.80 M2***

    ***SISTEMA MODULAR FARDO***

    ***COMPUESTA POR 2 BAÑOS, 2 DORMITORIOS, OFICINA Y ANEXOS DE COMEDOR COCINA***

    ***APLICACION EN EXTERIOR CAPA MORTERO ARCILLA +CAL***

    ***INSTALACION DE SUELO RADIANTE*** 

    ***ALIMENTACION ENERGETICA CON INSTALACION AISLADA*** 

    ***CALEFACCION CON EQUIPO DE AEROTERMIA***













    Revocos aplicados con arcilla, paja cribada mas hidroxido de cal.

    Instalacion de sistema de aerotermia con suelo radiante para calefaccion suelo refrescante en instalacion aislada.
    – Dirección: Molina de segura. Murcia
    – Latitud:
    – Longitud:
    – País: España
    – Provincia: Murcia
    – Año comienzo construcción: 2024
    – Año fin construcción: 2024
    – Metros cuadrados construidos: 104
    – Técnica constructiva: -Módulos Prefabricados
    – Dueño o promotor: Maria
    – Técnico(arquitecto o aparejador):
    – Empresa constructora: De tierra y paja
    – Carpintero: De Tierra y Paja
    – Revoques o acabados: Juan Antonio/  De cal y barro
    – Albañil:
    – Crédito de la casa:
    – Correo electronico: [josefsr2012@gmail.com](mailto:josefsr2012@gmail.com)
    – Enlace a sitio externo: [https://detierraypaja.com/](https://detierraypaja.com/)


    #### Project Info

    Category: MurciaDATE: Ene 22, 2025[Previous](https://www.casasdepaja.org/portfolio/proyecto-ibeas-de-juarros-burgos/)









- image: casas-pasivas-2024-07-17-08-29-01.jpg
  id: proyecto-2
  link: '#proyecto-2'
  title: Proyecto 2
  md: |
    Este es un ejemplo de un proyecto de construcción con módulos prefabricados de madera y balas de paja.

    La imagen muestra la estructura básica del módulo, que se ensamblará en el sitio para formar una vivienda sostenible.
- image: plano.webp
  id: proyecto-3
  link: '#proyecto-3'
  title: Proyecto 3
  md: |
    Este es un ejemplo de un proyecto de construcción con módulos prefabricados de madera y balas de paja.

    La imagen muestra la estructura básica del módulo, que se ensamblará en el sitio para formar una vivienda sostenible.
- image: casas-pasivas-2024-02-22-08-50-40.jpg
  id: proyecto-4
  link: '#proyecto-4'
  title: Proyecto 4
  md: |
    Este es un ejemplo de un proyecto de construcción con módulos prefabricados de madera y balas de paja.

    La imagen muestra la estructura básica del módulo, que se ensamblará en el sitio para formar una vivienda sostenible.
footer:
  color: dark
  div: curve-corner
  space: 2
  dots:
  - link: https://g.page/r/CU1QeFCO9R6yEAg
  - link: https://www.facebook.com/detierraypaja
  - link: https://www.instagram.com/detierraypaja/
  md: |
    - :copyright:      {{< internal-link index >}}
    - :scale-balanced: {{< internal-link legal >}}
    - :shield-keyhole: {{< internal-link privacy >}}
    - :cookie-bite:    {{< internal-link cookies >}}
    - :seacomoseo:     {{< i18n web_design >}} [seacomoseo.com](https://seacomoseo.com/)
    {.list-inline}
