title: Valores Globales
menu:
  image: base/logo-h.svg
  items:
  - link: /
    label: Inicio
  - link: /casas-pasivas/
    label: Casas Pasivas
  - link: /proyectos/
    label: Proyectos
  - link: /fardo/
    label: Fardo
  - link: /#contacto
    label: Contacto
    button: cta
  - link: https://agroecologiamurcia.org/
    label: Formación
    button: main
projects:
- image: casas-pasivas-2024-07-17-08-24-31.jpg
  id: proyecto-1
  link: '#proyecto-1'
  title: Proyecto 1
  md: |
    **VIVIENDA UNIFAMILIAR : CON CARBONO NEGATIVO ACUMULADO DE 2.100 kg por M3 de C2e**

    **AÑO CONSTRUCCION: 2023 EN LA REGION DE MURCIA**

    **M2 CONSTRUIDOS : 92 / UTILES: 82.80 M2**

    **SISTEMA MODULAR FARDO**

    **COMPUESTA POR 2 BAÑOS, 2 DORMITORIOS, OFICINA Y ANEXOS DE COMEDOR COCINA**

    **APLICACION EN EXTERIOR CAPA MORTERO ARCILLA +CAL**

    **INSTALACION DE SUELO RADIANTE**

    **ALIMENTACION ENERGETICA CON INSTALACION AISLADA**

    **CALEFACCION CON EQUIPO DE AEROTERMIA**
- image: casas-pasivas-2024-07-17-08-29-01.jpg
  id: proyecto-2
  link: '#proyecto-2'
  title: Proyecto 2
  md: |
    **VIVIENDA UNIFAMILIAR : CON CARBONO NEGATIVO ACUMULADO DE 1.050 kg de C2e**

    **AÑO CONSTRUCCION: 2024 EN LA REGION DE MURCIA**

    **M2 CONSTRUIDOS : 40 / UTILES: 32 M2**

    **SISTEMA MODULAR FARDO**

    **COMPUESTA POR 1 BAÑOS, 1 DORMITORIOS, ANEXOS DE COMEDOR COCINA**

    **APLICACION EN EXTERIOR CAPA MORTERO ARCILLA +CAL**

    **ALIMENTACION ENERGETICA CON INSTALACION AISLADA**

    **CALEFACCION CON EQUIPO DE AEROTERMIA**
- image: plano.webp
  id: proyecto-3
  link: '#proyecto-3'
  title: Proyecto 3
  md: |
    PENDIENTE DE EJECUTAR
- image: casas-pasivas-2024-02-22-08-50-40.jpg
  id: proyecto-4
  link: '#proyecto-4'
  title: Proyecto 4
  md: |
    **VIVIENDA UNIFAMILIAR : CON CARBONO NEGATIVO ACUMULADO DE 2.325 kg de C2e**

    **AÑO CONSTRUCCION: 2025 REGION DE MURCIA**

    **M2 CONSTRUIDOS : 104/ UTILES: 95 M2**

    **SISTEMA MODULAR FARDO**

    **COMPUESTA POR 2 BAÑOS, 2 DORMITORIOS,ANEXOS DE COMEDOR COCINA**

    **APLICACION EN EXTERIOR CAPA MORTERO ARCILLA +CAL**

    **INSTALACION DE SUELO RADIANTE**

    **ALIMENTACION ENERGETICA CON INSTALACION AISLADA**

    **CALEFACCION CON EQUIPO DE AEROTERMIA**
footer:
  color: dark
  div: curve-corner
  space: 2
  dots:
  - link: https://g.page/r/CU1QeFCO9R6yEAg
  - link: https://www.facebook.com/detierraypaja
  - link: https://www.instagram.com/detierraypaja/
  md: |
    - :copyright:      {{< internal-link index >}}
    - :scale-balanced: {{< internal-link legal >}}
    - :shield-keyhole: {{< internal-link privacy >}}
    - :cookie-bite:    {{< internal-link cookies >}}
    - :seacomoseo:     {{< i18n web_design >}} [seacomoseo.com](https://seacomoseo.com/)
    {.list-inline}
